### ISSUE TITLE
argument names

### ISSUE THREAD

**Issue by topepo** [business-science/modeltime#1]
Would it be possible to use more descriptive argument names? For example, maybe `non_seasonal_term` or similar for `p`. We try to avoid jargon with the names. 

Since the argument names are similar, maybe optimize them for tab-complete too.

**Comment by mdancho84** [comment]
Let me think about this. pdq and PDQ are used everywhere, but I agree that these are jargon. So let me think...

**Comment by mdancho84** [comment]
Ok, thought about it over the weekend. Here's what I propose for the `arima_reg` argument names and `dials` functions. @topepo __Let me know if you see any glaring issues.__ 

- __`period`__
- __`order_ar`__-  replaces `p()`
- __`order_differences`__ - replaces `d()`
- __`order_ma`__ - replaces `q()`
- __`order_seasonal_ar`__ - replaces `P()`
- __`order_seasonal_differences`__ - replaces `D()`
- __`order_seasonal_ma`__ - replaces `Q()`

This should help tab-complete and also improve the description. The only thing I don't like is that those familiar with PDQ-notation will likely expect to see that. But this should be a minor inconvenience. 

## Review of Modeling Packages & Terminology

Most packages use some form of jargon, which is PDQ notation. PDQ is essentially the:
- p = AR Order
- d = Number of Differences
- q = MA Process Order

Capitalized PDQ notation is the Seasonal version of pdq. 

A sampling of widely used time series packages:

- __[Stats (R)](https://rdrr.io/r/stats/arima.html):__ Uses `order` as (p,d,q) and seasonal order as (P,D,Q)
- __[Statsmodels ARIMA class (python)](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.html):__ Uses `order` as (p,d,q). This is likely based on R `stats::arima`
- __[Statsmodels SARIMAX (Seasonal ARIMA w/ Exogenous Regressors](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html?highlight=sarimax#statsmodels.tsa.statespace.sarimax.SARIMAX):__ Uses order (pdq) and seasonal_order (PDQs)
- __[Forecast Auto ARIMA](https://rdrr.io/cran/forecast/man/auto.arima.html):__ Uses `max.p`, `max.d`, `max.q`, etc
