### ISSUE TITLE
Dependency on Version of tidyselect

### ISSUE THREAD

**Issue by jaredlander** [business-science/modeltime#10]
I installed `{modeltime}` and had `{tidyselect}` version 0.2.5.

Trying to use function `plot_time_series()` resulted in this error.

```
Error: 'eval_select' is not an exported object from 'namespace:tidyselect'
```

Upgrading to `{tidyselect}` 1.1.0 fixed the problem.

So perhaps the `DESCRIPTION` file should import some minimal version of `{tidyselect}`, somewhere in (0.2.5 and 1.1.0].

**Comment by mdancho84** [comment]
Thanks @jaredlander - I'll up the requirement on `tidyselect`. It may be inside of `timetk` since this is where I use `eval_select()`. Will work it out either way. Thanks for the heads up.

**Comment by jaredlander** [comment]
I realized this morning it was `{timetk}` but you beat me to it.

**Comment by mdancho84** [comment]
Closing here and moving to the issue to `timetk`. I'll have it fixed today.
