### ISSUE TITLE
recipe on future_tbl

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#100]
In the example on: 

https://www.business-science.io/code-tools/2021/03/15/introducing-modeltime-h2o.html

... we see that a future_tbl gets a recipe:

`myFuture_prepared <- bake(prep(recipe_spec), future_tbl)`

In the video this seems not necessary:

https://youtu.be/mXWwxZBq5OM

What is the right way? What is the difference?

**Comment by ichsan2895** [comment]
Yes, I think, `bake(prep(recipe_spec), future_tbl)` is optional too. You can use it if you want add some columns which to be another predictor.

For example:
![image](https://user-images.githubusercontent.com/60387342/116207377-04924980-a76a-11eb-9477-5ab9616309a0.png)

![image](https://user-images.githubusercontent.com/60387342/116207465-1bd13700-a76a-11eb-901f-4d68f5fb3c45.png)

Thats it, new columns called `date_index.num`, `date_year`, `date_year.iso`, etc

**Comment by mdancho84** [comment]
I teach this in my time series course. Take the course to learn feature engineering both internal and external to workflows.
