### ISSUE TITLE
modeltime.h2o & future_frame()

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#101]
In https://github.com/business-science/modeltime/issues/24#issuecomment-678577920
you said: 

'For a 1-step or multi-step ahead forecasts that include XREGS (e.g. lags, events, etc), you need to use new_data providing all columns with the exception of the target column (optionally the target can be encoded as NA values). This means you need to supply the Xregs as part of the future data frame.'

Is this for modeltime.h2o the case too? Do the Xregs/Regressors have to have a value in the future_frame?

**Comment by mdancho84** [comment]
Yes. When you have regressors, you need to provide them so your algorithm can make a prediction.

**Comment by Steviey** [comment]
There are approaches to do this automatically, so the emphasis lies on value.
