### ISSUE TITLE
White Noise CI in ACF Plots

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [business-science/modeltime#116]
Hi @mdancho84 ,

I open this issue in `Modeltime` because it affects `plot_modeltime_residuals()`, specifically the ACF display but really it could be an issue in `timetk` because the function I would really like to talk about is `plot_acf_diagnostics()`.

I would like to propose to change the ".show_white_noise_bars" argument of this function by default to TRUE. I really don't understand what is the reason to have it default to FALSE, since seeing the confidence intervals (at least in my opinion) seems to me something really important in this visualization and therefore I think it should be already there from the beginning. Although it may seem silly to change it, it took me some time to realize which was the argument I had to modify to activate this option (in fact, at the beginning I thought that this option did not exist).

Let's comment.

Best regards,

**Comment by mdancho84** [comment]
OK, do me a favor and open an issue in `timetk` so we can track it. I don't have a problem with this.

**Comment by mdancho84** [comment]
This should work now with `timetk >= 0.6.1.9000`.

``` r
library(modeltime)
library(tidymodels)
library(tidyverse)
library(timetk)

# Data
m750 <- m4_monthly %>% filter(id == "M750")

# Split Data 80/20
splits <- initial_time_split(m750, prop = 0.9)

# --- MODELS ---

# Model 1: auto_arima ----
model_fit_arima <- arima_reg() %>%
    set_engine(engine = "auto_arima") %>%
    fit(value ~ date, data = training(splits))
#> frequency = 12 observations per 1 year
```

``` r
models_tbl <- modeltime_table(
    model_fit_arima
)
```

``` r
# In-Sample
models_tbl %>%
    modeltime_calibrate(new_data = training(splits)) %>%
    modeltime_residuals() %>%
    plot_modeltime_residuals(
        .type = "acf", 
        .white_noise_line_color = "red",
        .interactive = FALSE
    )
#> Max lag exceeds data available. Using max lag: 274
```

![](https://i.imgur.com/uvH6PkQ.png)

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
