### ISSUE TITLE
Modeltime Accuracy by ID Error

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [business-science/modeltime#127]
Hi @mdancho84 ,

I am running `modeltime_accuracy()` for different groups and I am encountering an error. I can't upload a reprex because I can't share the data, I open the issue just for traceability that there is this problem. If I run it without the `acc_by_id` argument everything works correctly, but as soon as I activate `acc_by_id = TRUE` it suddenly gives this error (this is in the current Modeltime version, without the changes I uploaded in the PR which is still pending). 

```
> calibration_tbl %>% modeltime_accuracy(acc_by_id = TRUE, quiet = FALSE)
Error: In metric: `mase`
Problem with `summarise()` column `.estimate`.
i `.estimate = metric_fn(...)`.
x `truth` must have a length greater than `m` to compute the out-of-sample naive mean absolute error.
i The error occurred in group 269: product_id = 1137500.
# A tibble: 1 x 3
  .model_id .model_desc .type
      <int> <chr>       <chr>
1         1 XGBOOST     Test 
Warning message:
modeltime_accuracy(): It looks like no accuracy metrics were returned. Try running with `modeltime_accuracy(quiet = FALSE)` to return error messages. 
```

**Comment by mdancho84** [comment]
Mase has issues. Try removing from the metric set.
