### ISSUE TITLE
Feature Request: residual and confidence interval extraction capability for ensemble models (panel input)

### ISSUE THREAD

**Issue by lg1000** [business-science/modeltime#149]
As your documentation of modeltime_residuals() indicates, there is no such capability for panel data. 

Using modeltime_calibrate() should give me what I need according to your documentation, but it does not in my particular case. 
Same issue I got with modeltime_forecast() which does not return any confidence values if I switch from single to panel input:
https://stackoverflow.com/questions/70212528/extracting-confidence-intervals-and-residuals-is-failing-for-recursive-panel-dat

My costumer wants me to develop a shiny app for visualization of the original time series tied together with the forecast results and also confidence intervals. All my attempts to do this for multiple series failed. Sure I could use a for loop to retrieve residuals and confidence intervals series by series, but that's just nuts.

**Comment by mdancho84** [comment]
Have you tried the new "calibrate by id" capability?

This gives you residuals by ID so you can get accuracy by ID and adjust the confidence intervals of panel forecasts by ID. 

You can see an example in the Global Forecasting tutorial. https://business-science.github.io/modeltime/articles/modeling-panel-data.html

**Comment by mdancho84** [comment]
I believe the problem in your example isn't `modeltime`, but rather the way you are creating your test_data, which does not have any values to compare predictions against. If your test data had values, you would get confidence intervals by ID following your example. 

``` r
# Time Series ML
library(tidymodels)
library(modeltime)
library(modeltime.ensemble)

# Core
library(tidyverse)
library(timetk)


FORECAST_HORIZON <- 24

data = m750    # -----------> Single time series input works fine!

# changing the input to panel results in NA for residuals conf_hi and conf_lo...
data <- m4_monthly %>%
    group_by(id) %>%
    future_frame(
        .length_out = FORECAST_HORIZON,
        .bind_data  = TRUE
    ) %>%
    ungroup()
#> .date_var is missing. Using: date

# data def
lag_transformer_grouped <- function(data){
    data %>%
        group_by(id) %>%
        tk_augment_lags(value, .lags = 1:FORECAST_HORIZON) %>%
        ungroup()
}

data_lags <- data %>%
    lag_transformer_grouped()

test_data <- data_lags %>%
    group_by(id) %>%
    slice_tail(n = 12) %>%
    ungroup()

test_data
#> # A tibble: 48 × 27
#>    id    date       value value_lag1 value_lag2 value_lag3 value_lag4 value_lag5
#>    <fct> <date>     <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>
#>  1 M1    2016-07-01    NA         NA         NA         NA         NA         NA
#>  2 M1    2016-08-01    NA         NA         NA         NA         NA         NA
#>  3 M1    2016-09-01    NA         NA         NA         NA         NA         NA
#>  4 M1    2016-10-01    NA         NA         NA         NA         NA         NA
#>  5 M1    2016-11-01    NA         NA         NA         NA         NA         NA
#>  6 M1    2016-12-01    NA         NA         NA         NA         NA         NA
#>  7 M1    2017-01-01    NA         NA         NA         NA         NA         NA
#>  8 M1    2017-02-01    NA         NA         NA         NA         NA         NA
#>  9 M1    2017-03-01    NA         NA         NA         NA         NA         NA
#> 10 M1    2017-04-01    NA         NA         NA         NA         NA         NA
#> # … with 38 more rows, and 19 more variables: value_lag6 <dbl>,
#> #   value_lag7 <dbl>, value_lag8 <dbl>, value_lag9 <dbl>, value_lag10 <dbl>,
#> #   value_lag11 <dbl>, value_lag12 <dbl>, value_lag13 <dbl>, value_lag14 <dbl>,
#> #   value_lag15 <dbl>, value_lag16 <dbl>, value_lag17 <dbl>, value_lag18 <dbl>,
#> #   value_lag19 <dbl>, value_lag20 <dbl>, value_lag21 <dbl>, value_lag22 <dbl>,
#> #   value_lag23 <dbl>, value_lag24 <dbl>
```

<sup>Created on 2021-12-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lg1000** [comment]
Thanks! Your comment just saved my week. As my customer is pressing hard, I tend to make mistakes, that do not happen under normal circumstances. The problem started with the definition of the object "data". I will post my solution on SO and close the issue

**Comment by mdancho84** [comment]
That sounds great! Glad it's solved.
