### ISSUE TITLE
seasonal decomp tests producing errors

### ISSUE THREAD

**Issue by robjhyndman** [business-science/modeltime#151]
The tests in `test-algo-seasonal_decomp_arima.R` and `test-algo-seasonal_decomp_ets.R` are producing errors using the current dev version of the forecast package. Can you please fix them and update on CRAN so I can release a new version of the forecast package. (I don't *think* it is an error in the forecast package. Most likely, [this change](https://github.com/robjhyndman/forecast/commit/0fca5c511741b8398a89233ad112ee45f0f590a2#diff-36e606d5c540db8a0737c1801f2b540b377d6fa4303fe7db600cd220e38ed657) has led to small differences in what is returned. But if you think it is my error, please let me know.)

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-algo-seasonal_decomp_arima.R:79:5): seasonal_reg - arima: parnip ──
max(abs(resid)) is not less than 2500. Difference: 5.47e+03
── Failure (test-algo-seasonal_decomp_arima.R:82:5): seasonal_reg - arima: parnip ──
mean(abs(resid)) is not less than 700. Difference: 3.42e+03
── Failure (test-algo-seasonal_decomp_arima.R:150:5): seasonal_reg: workflow ───
max(abs(resid)) is not less than 2500. Difference: 5.47e+03
── Failure (test-algo-seasonal_decomp_arima.R:153:5): seasonal_reg: workflow ───
mean(abs(resid)) is not less than 700. Difference: 3.42e+03
── Failure (test-algo-seasonal_decomp_ets.R:79:5): seasonal_reg: parnip ────────
max(abs(resid)) is not less than 2500. Difference: 5.39e+03
── Failure (test-algo-seasonal_decomp_ets.R:82:5): seasonal_reg: parnip ────────
mean(abs(resid)) is not less than 700. Difference: 3.43e+03
── Failure (test-algo-seasonal_decomp_ets.R:142:5): seasonal_reg: workflow ─────
max(abs(resid)) is not less than 2500. Difference: 5.39e+03
── Failure (test-algo-seasonal_decomp_ets.R:145:5): seasonal_reg: workflow ─────
mean(abs(resid)) is not less than 700. Difference: 3.43e+03
```

**Comment by mdancho84** [comment]
Hey @robjhyndman thanks for the heads up on this. Let me take a look today and get back to you. It's a little weird that the accuracy is getting worst by so much so let me see what's happening. Thanks!!

**Comment by mdancho84** [comment]
@robjhyndman I'm investigating now and here's what I'm seeing. It looks like the Seasonal Decomp with ARIMA isn't picking up the seasonality as well as it previously did. 

Let me know what you think about this - The bottom line is I will follow your lead. If these results are OK for you / what you want, then simply submit to CRAN and I will update modeltime tests to make these results PASS. 

# Results

This example uses the taylor 30-min with multiple seasonality at 48 (obs per day) and 336 (obs per week).

Forecast with train + test
![image](https://user-images.githubusercontent.com/13734662/148562340-9dc92290-a135-43b6-a3ee-78d855236f86.png)

Forecast with just test to zoom in
![image](https://user-images.githubusercontent.com/13734662/148561772-5b9540a0-ca59-4595-8e97-4a34fc371e59.png)

Decomposition Plot
![image](https://user-images.githubusercontent.com/13734662/148562016-c82363d2-b71b-4f2d-9b8d-ca08739d7e76.png)


# Code to Reproduce

``` r
# Libraries
library(tidymodels)
library(modeltime)
library(tidyverse)
library(timetk)
library(lubridate)

# Data used
taylor_30_min
#> # A tibble: 4,032 x 2
#>    date                value
#>    <dttm>              <dbl>
#>  1 2000-06-05 00:00:00 22262
#>  2 2000-06-05 00:30:00 21756
#>  3 2000-06-05 01:00:00 22247
#>  4 2000-06-05 01:30:00 22759
#>  5 2000-06-05 02:00:00 22549
#>  6 2000-06-05 02:30:00 22313
#>  7 2000-06-05 03:00:00 22128
#>  8 2000-06-05 03:30:00 21860
#>  9 2000-06-05 04:00:00 21751
#> 10 2000-06-05 04:30:00 21336
#> # ... with 4,022 more rows

# Split into train/test
splits <- initial_time_split(taylor_30_min, prop = 0.9)

# Create a Model Spec
model_spec <- seasonal_reg(
        seasonal_period_1 = "1 day", 
        seasonal_period_2 = "week"
    ) %>%
    set_engine("stlm_arima")

# Fit a Model 
model_fit <- model_spec %>%
    fit(log(value) ~ date + wday(date, label = TRUE), data = training(splits))
#> frequency = 48 observations per 1 day
#> frequency = 336 observations per 1 week

# Calibrate model to Test data
model_tbl <- modeltime_table(model_fit) %>%
    modeltime_calibrate(testing(splits))
    

# Plot 1 - Forecast with train + test
model_tbl %>%
    modeltime_forecast(
        new_data    = testing(splits),
        actual_data = bind_rows(training(splits), testing(splits))
    ) %>%
    plot_modeltime_forecast(.interactive = F)
#> Warning in max(ids, na.rm = TRUE): no non-missing arguments to max; returning
#> -Inf
```

![](https://i.imgur.com/kQLQZ1j.png)

``` r
# Plot 2 - Forecast with just test to zoom in
model_tbl %>%
    modeltime_forecast(
        new_data    = testing(splits),
        actual_data = testing(splits)
    ) %>%
    plot_modeltime_forecast(.interactive = F)
#> Warning in max(ids, na.rm = TRUE): no non-missing arguments to max; returning
#> -Inf
```

![](https://i.imgur.com/iyhyILa.png)

``` r
# Plot 3 - Seasonal Decomposition Plot
model_fit$fit$models$model_1$stl %>% plot()
```

![](https://i.imgur.com/ONF69Qu.png)

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by robjhyndman** [comment]
Thanks. Definitely my problem! Fixed in https://github.com/robjhyndman/forecast/commit/c4960da08c6eb62b5612b9003d72ee415d1e4888

**Comment by mdancho84** [comment]
Ok I'm glad you found the issue. Thanks!
