### ISSUE TITLE
[[PR pending]] damping_smooth() has a bug...

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#156]
Easy to fix...

Function **dials::new_qual_param()** has no param 'inclusive':

Compare:

https://dials.tidymodels.org/reference/new-param.html

https://github.com/business-science/modeltime/blob/master/R/dials-ets_params.R

... I think it's intended damping_smooth() to be a quantitative param.

```
algoTrainCase   <-'gridMaxEntropy' # 7,23
#algoTrainCase   <-'gridLatin' # 7,81
ret$modelObj    <- exp_smoothing(
	error          = tune()
	,trend         = tune()
	,season        = tune()
	,damping       = tune()
	,smooth_level  = tune()
	,smooth_trend  = tune()
) %>%
set_engine("smooth_es",holdout=FALSE)
ret$finalParams <- ret$modelObj %>% parameters() #%>% finalize(x=trainPart)
ret$finalParams <- updateMyParams(ret$finalParams,subModel,taskSwitch,trainSetupList)


Error: Problem with `mutate()` column `object`.
ℹ `object = purrr::map(call_info, eval_call_info)`.
x Error when calling damping_smooth(): Error in dials::new_qual_param(type = "double", range = range, inclusive = c(TRUE,  : 
  unused arguments (range = range, inclusive = c(TRUE, TRUE))
```
  
 **Further discussions** on smooth_es-integration in modeltime.ensemble...
https://github.com/config-i1/smooth/issues/192

**Awaiting instructions** on pull-requests...
https://community.rstudio.com/t/how-to-test-modeltime-pull-requests-commits-locally/127619

**Comment by Steviey** [comment]
Update: I thought I made a PR, but I get the message: 'This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.'

**Comment by mdancho84** [comment]
I haven't seen any PRs come across. I recommend using `usethis` to do pull requests. https://usethis.r-lib.org/articles/pr-functions.html

**Comment by Steviey** [comment]
Did it with VS-Code + Github.

**Comment by mdancho84** [comment]
Just approved! Thanks for fixing this!!
