### ISSUE TITLE
New Feature Request drop_modeltime_table

### ISSUE THREAD

**Issue by neural-oracle** [business-science/modeltime#160]
Pls could you add a new feature to modeltime, that drops models from the modeltime_table?
So the opposite to the already available add_modeltime_table.

This would be great, since during ensembling with modeltime.ensemble the new ensemble_model gets added to the modeltime_table. However, during experimentation it could be great to drop bad ensembles.
Apart from ensembling, dropping inferior models would be great.

Thx ... modeltime is huge!

**Comment by mdancho84** [comment]
This is completed. https://business-science.github.io/modeltime/reference/drop_modeltime_model.html
