### ISSUE TITLE
defaulting to model = "ZXZ"

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#162]
Is there a reason why adam_reg(), engine auto.adam defaults to model = "ZXZ"? According to Ivans book, this translates to 'additive trends only'?
https://openforecast.org/adam/ETSSelection.html

**Comment by config-i1** [comment]
This is the default value in adam(). The additive trend model is more robust than the multiplicative one.

**Comment by AlbertoAlmuinha** [comment]
The default values are the same that Ivan selected in his `smooth` package, "ZXZ" for both `adam()` and `auto_adam()`. I can't see any reason to change the default values, honestly.

I think this issue should be closed for the moment.

**Comment by mdancho84** [comment]
I'm closing this per @AlbertoAlmuinha 's comment.
