### ISSUE TITLE
Confusing error message, when forecasting on future_tbl

### ISSUE THREAD

**Issue by lg1000** [business-science/modeltime#164]
After successfully running modeltime_forecast on my test data, I wanted to refit the model to forecast forward into the future. Unfortunately I receive the following error message, which I am not able to interpret:
<img width="814" alt="REFIT_ERROR" src="https://user-images.githubusercontent.com/27286618/157855539-d50624b7-e552-4686-b3d3-d9ad8ecba835.png">

As you can see, the error message complains about uneven factor levels in column 18, whereas there is no column 18. Both, data_prepared_tbl and future_tbl only consist of 14 columns. 

How can I interpret such an error?

**Comment by lg1000** [comment]
I just did another trial run excluding RANGER from the original submodels table (RANGER, XGBOOST, PROPHET W XGBOOST ERRORS). Now the forecast does work. Don't know, why RANGER is making a problem here. Probably the different approach of factor one-hot encoding

**Comment by AlbertoAlmuinha** [comment]
I think this issue could be closed because it seems to be more related with the particular algorithm and the preprocessing steps and not with `modeltime`.
