### ISSUE TITLE
What is the best model / funtion in modeltime to perform intraday prediction?

### ISSUE THREAD

**Issue by neuropil** [business-science/modeltime#175]
Do you have a tutorial on intraday data prediction? Which model would be best?

Thanks!
John

**Comment by vidarsumo** [comment]
You could try Prophet, setting seasonality_daily = TRUE. 

Another option, which I prefer, is to use any of the  boosted trees (XGBoost, Catboost or Light GBM) and simply create all the necessary features. `step_timeseries_signature()` is important here and also create lagged values of the outcome.

**Comment by neuropil** [comment]
thank you!
