### ISSUE TITLE
.conf_lo & .conf_hi are not matching the confidence levels in Prophet

### ISSUE THREAD

**Issue by saracmbr** [business-science/modeltime#176]
I've been trying to compare the forecast values and confidence values in prophet and model_time. .value matched the yhat in prophet model but the confidence values not. here is the working example. I'm using confidence interval of 0.95 for both.

M750 <- m4_monthly %>% filter(id == "M750") %>% select(-id)
names(M750)[1]='ds'
names(M750)[2]='y'

train_data <- training(initial_time_split(M750, prop = .8))

test_data <- testing(initial_time_split(M750, prop = .8))

model_fit_prophet <- prophet_reg() %>%
  set_engine(engine = "prophet" ) %>%
  fit(y ~ ds, data = train_data)

models_claib_tbl = model_fit_prophet %>%
  modeltime_calibrate(new_data = test_data,quiet = FALSE)
   

prediction = models_claib_tbl %>%
  modeltime_forecast(
    conf_interval = 0.95,
    new_data    = test_data,
    actual_data = Booster1 
    )

m <- prophet(train_data , interval.width = 0.95 )
future <- make_future_dataframe(m, periods =nrow(test_data), freq = "month",include_history = FALSE)
forecast <- predict(m, future)

prediction %>% filter(.model_desc=='PROPHET') %>% select(.index,.value,.conf_lo,.conf_hi) %>%
inner_join (forecast %>% select('ds', 'yhat', 'yhat_lower', 'yhat_upper'), by = c('.index'='ds'))

**Comment by mdancho84** [comment]
We implement our own algorithm for calculating confidence intervals, so they will not match. Instead, all algorithms use the test set residual error to determine CI, which is what happens when you use `modeltime_calibrate()`
