### ISSUE TITLE
modeltime_calibrate Input error with summarise() function FOUND THE ISSUE SOLUTION

### ISSUE THREAD

**Issue by PG-Ayaney** [business-science/modeltime#177]
Hello! It seems that modeltime_calibrate is returning an error:
![image](https://user-images.githubusercontent.com/78475003/167254020-1828c00e-bc2f-4b3a-8269-f9160f83cc46.png)

Code:
library(modeltime)
library(tidymodels)
library(tidyverse)
library(timetk)
library(lubridate)
library(doParallel)

registerDoParallel(cores = detectCores())

trainSet2 <- read.csv("trainSet2.csv")
testSet2 <- read.csv("testSet2.csv")
trainSet2$Fecha <- as.Date(trainSet2$Fecha)
testSet2$Fecha <- as.Date(testSet2$Fecha)

model_arima <- arima_reg() %>% set_engine("auto_arima") %>% fit(Inventario ~ Fecha, trainSet2)
model_prophet <- prophet_reg() %>% set_engine("prophet") %>% fit(Inventario ~ Fecha, trainSet2)
model_glmnet <- linear_reg(penalty = 0.01) %>% set_engine("glmnet") %>% 
                fit(Inventario ~ wday(Fecha, label=TRUE) + month(Fecha, label=TRUE) + as.numeric(Fecha), trainSet2)

model_tbl <- modeltime_table(model_arima,model_prophet,model_glmnet)

calib_tbl <- model_tbl %>% modeltime_calibrate(quiet = FALSE, values_fn = list, new_data =  testSet2)

calib_tbl %>% modeltime_accuracy()

Data:
[testSet2.csv](https://github.com/business-science/modeltime/files/8645113/testSet2.csv)
[trainSet2.csv](https://github.com/business-science/modeltime/files/8645114/trainSet2.csv)

Error Msg:
Error: Problem with `summarise()` input `.calibration_data`.
x Tibble columns must have compatible sizes.
* Size 131: Existing data.
* Size 45: Column `.actual`.
i Only values of size one are recycled.
i Input `.calibration_data` is `list(...)`.
i The error occured in group 1: .type = "Test".
Error: Problem with `summarise()` input `.calibration_data`.
x Tibble columns must have compatible sizes.
* Size 131: Existing data.
* Size 45: Column `.actual`.
i Only values of size one are recycled.
i Input `.calibration_data` is `list(...)`.
i The error occured in group 1: .type = "Test".
Error: Problem with `summarise()` input `.calibration_data`.
x Tibble columns must have compatible sizes.
* Size 131: Existing data.
* Size 45: Column `.actual`.
i Only values of size one are recycled.
i Input `.calibration_data` is `list(...)`.
i The error occured in group 1: .type = "Test".
Warning messages:
1: Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates 
2: Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates 
3: Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates

**Comment by PG-Ayaney** [comment]
I found the issue! ERROR arises when data given to modeltime_calibrate has duplicate values!

The function modeltime_calibrate must have in some point some unique() command to make the .actual column. To fix this the unique transformation must be executed for both data transformation or not at all or give an appropiate "Found duplicates error" message.

Cheers!

**Comment by PG-Ayaney** [comment]
Code with no error rised:
library(modeltime)
library(tidymodels)
library(tidyverse)
library(timetk)
library(lubridate)
library(doParallel)

registerDoParallel(cores = detectCores())

trainSet2 <- read.csv("trainSet2.csv")
testSet2 <- read.csv("testSet2.csv")
trainSet2$Fecha <- as.Date(trainSet2$Fecha)
testSet2$Fecha <- as.Date(testSet2$Fecha)
trainSet2 <- as_tibble(trainSet2)
trainSet2  <- unique(trainSet2)
testSet2 <- as_tibble(testSet2)
testSet2  <- unique(testSet2)

model_arima <- arima_reg() %>% set_engine("auto_arima") %>% fit(Inventario ~ Fecha, trainSet2)
model_prophet <- prophet_reg() %>% set_engine("prophet") %>% fit(Inventario ~ Fecha, trainSet2)
model_glmnet <- linear_reg(penalty = 0.01) %>% set_engine("glmnet") %>%
fit(Inventario ~ wday(Fecha, label=TRUE) + month(Fecha, label=TRUE) + as.numeric(Fecha), trainSet2)

model_tbl <- modeltime_table(model_arima,model_prophet,model_glmnet)

calib_tbl <- model_tbl %>% modeltime_calibrate(quiet = FALSE, values_fn = list, new_data = testSet2)

calib_tbl %>% modeltime_accuracy()

**Comment by mdancho84** [comment]
Excellent! Closing issue.
