### ISSUE TITLE
WISH: Less aggressive parallelization by default (please don't use *all* CPU cores)

### ISSUE THREAD

**Issue by HenrikBengtsson** [business-science/modeltime#178]
Hi, while running deep reverse dependency checks on **globals**, I noticed that **modeltime** parallelizes on _all_ CPU cores.  Looking at the code, it looks like this is configured here:

https://github.com/business-science/modeltime/blob/b896d61037864067227eee941bf7da6229f0be29/R/utils-control-par.R#L389-L392

Defaulting to all cores causes major problems on machines used by multiple users, but also when there are software tools running at the same time. I spotted this on a 128 CPU core machine. Imagine running another 10-20 processes like that at the same time on this machine - it'll quickly come to a halt, which is a real problem.  This will also happen if you run multiple instance of **modeltime** on the same machine.

Although the behavior can be changed by setting an R option, many users are not aware of the problem ... until the sysadms yell at them. Also, **modeltime** might be running deep down as a dependency that other package maintainers might not be aware of, so this behavior might be inherited also be other packages without them knowing.

Could you please consider switch the default to be more conservative? Personally, I'm in the camp that everything should run sequentially (single-core), unless the user configures it otherwise. CRAN has a limit of two CPU cores.

(Disclaimer: I'm the author) If you don't want to do this, could you please consider changing from:

```r
parallel::detectCores(logical = FALSE)
```

to

```r
parallelly::availableCores(logical = FALSE)
```

because the latter gives sysadms a chance to limit it on their end, and it also respects CGroups settings, job scheduler allocations, etc. Another example is RStudio Cloud. Depending on account, a user might have access to, say, 1 or 4 CPU cores, although `detectCores()` reports on the underlying 16 cores.  If such a user runs **modeltime**, your current code will set up 16 workers that compete with the 1 or 4 cores that RStudio Cloud allows it run run on (Cgroups).  See https://parallelly.futureverse.org/#availablecores-vs-paralleldetectcores for more details.

Thank you

**Comment by mdancho84** [comment]
This one should be completed.

**Comment by jaredlander** [comment]
I'm not sure the fix went through entirely. I'm running `{modeltime}` 1.2.2 inside of `{targets}`. I use `targets::tar_make_future(..., workers=10)`. In this particular case I am fitting seven models in separate (parallel) targets. Once I hit that step all 16 of my cores are pegged.

So I think what's happening is that I am running seven models in parallel via `{targets}`, each of which are using multiple cores, overloading the actually available number of cores.
