### ISSUE TITLE
Split issue with model_time and timetk in R

### ISSUE THREAD

**Issue by rgs-minu** [business-science/modeltime#184]
i'm using modeltime to forecast 20 time series (not balanced) at once using [Modeltime](https://cran.r-project.org/web/packages/modeltime/vignettes/getting-started-with-modeltime.html) package. However, when I call the function modeltime_calibrate i got the following error:

`Error in glubort(): ! Missing 'new_data'. Try adding a test data set using rsample::testing(splits). See help for more info: ?modeltime_calibrate`

Its seems to be related to split, but I couldn't find any explanation:

`splits <Analysis/Assess/Total> <887/20/907>`

Follow my code. Thanks, Rick

```
splits <- data %>% time_series_split(assess = "3 months", cumulative = TRUE)
splits %>%
  tk_time_series_cv_plan() %>%
  plot_time_series_cv_plan(date, value, .interactive = TRUE)

rec_obj <- recipe(value ~ ., training(splits)) %>%
  step_mutate(ID = droplevels(ID)) %>%
  step_timeseries_signature(date) %>%
  step_rm(date) %>%
  step_zv(all_predictors()) %>%
  step_dummy(all_nominal_predictors(), one_hot = TRUE)
summary(prep(rec_obj))

wflw_xgb <- workflow() %>%
  add_model(
    boost_tree() %>% set_engine("xgboost")
  ) %>%
  add_recipe(rec_obj) %>%
  fit(training(splits))
wflw_xgb

model_tbl <- modeltime_table(
  wflw_xgb
)
model_tbl

calib_tbl <- model_tbl %>%
  modeltime_calibrate(
    new_data = testing(splits), 
    id       = "ID",
    modeltime_calibrate(quiet = FALSE)
  )
calib_tbl
```

**Comment by AlbertoAlmuinha** [comment]
Hi,

It's very difficult to debug if we don't have a reproducible example and we can't see the data. But what I can tell is that the last part of the code is wrong, it should be:

```
calib_tbl <- model_tbl %>%
  modeltime_calibrate(
    new_data = testing(splits), 
    id       = "ID",
    quiet    = FALSE
  )
calib_tbl
```

You have introduced a second call to `modeltime_calibrate()` into the first one and that's incorrect. If the rest of the code it's ok, that should work.

Regards,
