### ISSUE TITLE
Error when trying to forecast on subsample of the data with recursive model

### ISSUE THREAD

**Issue by vidarsumo** [business-science/modeltime#187]
Hi Matt,

I get an error if I try to forecast on subsample of the data with recursive model.

```
# Packages
library(tidymodels)
library(modeltime)
library(timetk)


# Lag function for recursive forecasting
lag_function <- function(data) {
    data %>% 
        arrange(id, Date) %>% 
        group_by(id) %>% 
        tk_augment_lags(Weekly_Sales, .lags = 1:12) %>% 
        ungroup()
        
}


# Data preparation
data_tbl <- timetk::walmart_sales_weekly %>% 
    select(id, Date, Dept, Weekly_Sales) %>% 
    lag_function()

splits <- timetk::time_series_split(data = data_tbl, date_var = Date, assess = 12, cumulative = TRUE)


# Build model
recipe_spec <- recipe(Weekly_Sales ~ ., data = training(splits)) %>% 
    step_rm(Date) %>% 
    step_dummy(all_nominal_predictors()) %>% 
    step_zv(all_predictors())


model_spec <- boost_tree(mode = "regression", engine = "xgboost")

# Recursive model
recursive_model <- workflow() %>% 
    add_recipe(recipe_spec) %>% 
    add_model(model_spec) %>% 
    fit(training(splits)) %>% 
    modeltime::recursive(
        id = "id",
        transform = lag_function,
        train_tail = panel_tail(training(splits), id, 12)
    ) %>% 
    modeltime_table()

# Non-recursive model
non_recursive_model <- workflow() %>% 
    add_recipe(recipe_spec) %>% 
    add_model(model_spec) %>% 
    fit(training(splits)) %>% 
    modeltime_table()




# Non recursive model
fc_tbl <- non_recursive_model %>% 
    modeltime_forecast(
        new_data = testing(splits) %>% filter(!id == "1_1"),
        actual_data = splits$data %>% filter(!id == "1_1"),
        keep_data = TRUE
    )


# Recursive model
fc_tbl <- recursive_model %>% 
    modeltime_forecast(
        new_data = testing(splits) %>% filter(!id == "1_1"),
        actual_data = splits$data %>% filter(!id == "1_1"),
        keep_data = TRUE
    )
```
Error: Assigned data `pred_fun(...)` must be compatible with row subscript `new_data$rowid.. == i`.
✖ 6 rows must be assigned.
✖ Assigned data has 7 rows.
ℹ Only vectors of size 1 are recycled.
Error in `dplyr::filter()`:
! Problem while computing `..1 = .model_desc == "ACTUAL" | .key == "prediction"`.
Caused by error:
! object '.key' not found
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unknown or uninitialised column: `.key`.

**Comment by AlbertoAlmuinha** [comment]
Hi @vidarsumo ,

I hope everything will be just fine!

The problem with recursive is that it saves internal information when the model is defined and therefore if it is filtered later the information is corrupted.

If you want to filter the information, you have to do it also when you define the model, as follows:

```
# Recursive model
recursive_model <- workflow() %>% 
  add_recipe(recipe_spec) %>% 
  add_model(model_spec) %>% 
  fit(training(splits)) %>% 
  modeltime::recursive(
    id = "id",
    transform = lag_function,
    train_tail = panel_tail(training(splits)  %>% filter(!id == "1_1"), id, 12)
  ) %>% 
  modeltime_table()

# Recursive model
fc_tbl <- recursive_model %>% 
  modeltime_forecast(
    new_data = testing(splits) %>% filter(!id == "1_1"),
    actual_data = splits$data %>% filter(!id == "1_1"),
    keep_data = TRUE
  ) %>%
  plot_modeltime_forecast()
```

Regards,

**Comment by vidarsumo** [comment]
Hi Alberto,

The thing is that I have a dataset with 15.000 time series but 10.000 are old products that are not needed in the final forecast. These old products are really important for the model to learn patterns for new products. So removing them will harm the accuracy of new products. 

Is this something that is difficult to change?

**Comment by AlbertoAlmuinha** [comment]
Hi Vidar,

Okk, I perfect understand. As I put in some other issue out there, I think it would be good to take a look at it yes. Let's see if I can find some time to see it.

I'll let you know if there's any news.

**Comment by AlbertoAlmuinha** [comment]
Ok, this is solved.

I will submit a pull request in the following days with the changes.

Regards,
