### ISSUE TITLE
indicators in fit()

### ISSUE THREAD

**Issue by topepo** [business-science/modeltime#2]
I noticed this argument in the `fit()` method. We are working on a general way to control if indicators are produced in a model-specific way in `parsnip` (that would also be used by `workflows`). This is related to tidymodels/parsnip#290 and tidymodels/workflows#34

I'm in the process of implementing this and it probably won't be ready for about a month (so hopefully that wouldn't disqualify it). A prototype of the user-facing code is [here](https://github.com/tidymodels/parsnip/commit/c1dbac0f4efebd2a49120cb0d8f5c49265a480a4#diff-5a53a79f1337e80ed8975500b08eba1d).

**Comment by mdancho84** [comment]
Yes! This is much preferred over my hackish solution for indicator variables. I also see that creating a `recipe()` preserves the indicator variables, so I will transition to that approach for development.

**Comment by mdancho84** [comment]
@topepo My plan is to remove the fit methods as soon as tidymodels/parsnip#290 and tidymodels/workflows#34 are released to CRAN. I understand this could take a bit. Since this will have no effect on user experience, I'm going to wait to change. Leaving the issue open for now.

**Comment by mdancho84** [comment]
This is closed with #8
