### ISSUE TITLE
Modeltime 'updates' Arima specs when running the model on full data

### ISSUE THREAD

**Issue by B81L** [business-science/modeltime#206]
Hi, I am really new to forecasting and modeltime is a really great tool!
I just have a question though - When running the training data, and check the accuracy of models, I get the Arima model specs (2,1,1) which seem to be doing a pretty good job on the data, but then when I run the model on the full data in 'updates' to Arima (0,1,1)
i use the following code:
future_forecast_tbl <- calib_tbl %>%
  modeltime_refit(data) %>%
  modeltime_forecast(h = "12 month", actual_data = data)

Is there a way to stop this 'update' and keep the original Arima specs?
i look forward to a response. 
many thanks.

![2022-10-04 14_31_49-RStudio](https://user-images.githubusercontent.com/111324112/193728532-fb1a65a8-c85e-47fb-b9f6-1d8ae51bed3a.png)

**Comment by mdancho84** [comment]
When you use auto arima engine, the algorithm is "automatic" meaning it decides which arima model parameters to use. 

I don't have an easy way to toggle off the automatic update. 

But what you can do is request it as a feature. [See here.](https://business-science.github.io/modeltime/reference/arima_boost.html) 

In the meantime, you could alternatively create a model just using regular arima_boost engine and specify the arima model parameters. 

![image](https://user-images.githubusercontent.com/13734662/193802044-d49fa7f4-d158-475f-8ce5-6913688b8c93.jpeg)

**Comment by B81L** [comment]
Many Thanks!
that has worked for me - I can tweak the arima boost, based on the auto arima and that gives me some good results!
