### ISSUE TITLE
arima_boost strange prediction

### ISSUE THREAD

**Issue by Vidaringa** [business-science/modeltime#21]
I'm not sure if this is a bug or what. I followd the "Getting started" post on Modeltime but on my own time series. I did not change the XGBoost parameters (min_n = 2 and learning_rate 0 0.015). The prediction is totally off, see graph. Why is this happening, any idea?

![image](https://user-images.githubusercontent.com/20194883/90400169-9b5f2000-e08b-11ea-8fa5-998c78fb9fd5.png)

**Comment by mdancho84** [comment]
@Vidaringa 
Are you able to provide a reproducible example?

**Comment by Vidaringa** [comment]
```
library(tidymodels)
library(modeltime)
library(tidyverse)
library(lubridate)
library(timetk)

splits <- initial_time_split(ml_ts, prop = 0.98)

model_fit_arima_boosted <- arima_boost(
    min_n = 10,
    learn_rate = 0.015
) %>% 
    set_engine(engine = "auto_arima_xgboost") %>% 
    fit(value ~ date + as.numeric(date) + factor(lubridate::month(date, label = TRUE), ordered = F),
        data = training(splits))


models_tbl <- modeltime_table(
    model_fit_arima_boosted
)

calibration_tbl <- models_tbl %>% 
    modeltime_calibrate(new_data = testing(splits))

calibration_tbl %>% 
    modeltime_forecast(
        new_data    = testing(splits),
        actual_data = ml_ts 
    ) %>% 
    plot_modeltime_forecast(
        .interactive = TRUE
    )
```

data:

structure(list(date = structure(c(7336, 7364, 7395, 7425, 7456, 
7486, 7517, 7548, 7578, 7609, 7639, 7670, 7701, 7729, 7760, 7790, 
7821, 7851, 7882, 7913, 7943, 7974, 8004, 8035, 8066, 8095, 8126, 
8156, 8187, 8217, 8248, 8279, 8309, 8340, 8370, 8401, 8432, 8460, 
8491, 8521, 8552, 8582, 8613, 8644, 8674, 8705, 8735, 8766, 8797, 
8825, 8856, 8886, 8917, 8947, 8978, 9009, 9039, 9070, 9100, 9131, 
9162, 9190, 9221, 9251, 9282, 9312, 9343, 9374, 9404, 9435, 9465, 
9496, 9527, 9556, 9587, 9617, 9648, 9678, 9709, 9740, 9770, 9801, 
9831, 9862, 9893, 9921, 9952, 9982, 10013, 10043, 10074, 10105, 
10135, 10166, 10196, 10227, 10258, 10286, 10317, 10347, 10378, 
10408, 10439, 10470, 10500, 10531, 10561, 10592, 10623, 10651, 
10682, 10712, 10743, 10773, 10804, 10835, 10865, 10896, 10926, 
10957, 10988, 11017, 11048, 11078, 11109, 11139, 11170, 11201, 
11231, 11262, 11292, 11323, 11354, 11382, 11413, 11443, 11474, 
11504, 11535, 11566, 11596, 11627, 11657, 11688, 11719, 11747, 
11778, 11808, 11839, 11869, 11900, 11931, 11961, 11992, 12022, 
12053, 12084, 12112, 12143, 12173, 12204, 12234, 12265, 12296, 
12326, 12357, 12387, 12418, 12449, 12478, 12509, 12539, 12570, 
12600, 12631, 12662, 12692, 12723, 12753, 12784, 12815, 12843, 
12874, 12904, 12935, 12965, 12996, 13027, 13057, 13088, 13118, 
13149, 13180, 13208, 13239, 13269, 13300, 13330, 13361, 13392, 
13422, 13453, 13483, 13514, 13545, 13573, 13604, 13634, 13665, 
13695, 13726, 13757, 13787, 13818, 13848, 13879, 13910, 13939, 
13970, 14000, 14031, 14061, 14092, 14123, 14153, 14184, 14214, 
14245, 14276, 14304, 14335, 14365, 14396, 14426, 14457, 14488, 
14518, 14549, 14579, 14610, 14641, 14669, 14700, 14730, 14761, 
14791, 14822, 14853, 14883, 14914, 14944, 14975, 15006, 15034, 
15065, 15095, 15126, 15156, 15187, 15218, 15248, 15279, 15309, 
15340, 15371, 15400, 15431, 15461, 15492, 15522, 15553, 15584, 
15614, 15645, 15675, 15706, 15737, 15765, 15796, 15826, 15857, 
15887, 15918, 15949, 15979, 16010, 16040, 16071, 16102, 16130, 
16161, 16191, 16222, 16252, 16283, 16314, 16344, 16375, 16405, 
16436, 16467, 16495, 16526, 16556, 16587, 16617, 16648, 16679, 
16709, 16740, 16770, 16801, 16832, 16861, 16892, 16922, 16953, 
16983, 17014, 17045, 17075, 17106, 17136, 17167, 17198, 17226, 
17257, 17287, 17318, 17348, 17379, 17410, 17440, 17471, 17501, 
17532, 17563, 17591, 17622, 17652, 17683, 17713, 17744, 17775, 
17805, 17836, 17866, 17897, 17928, 17956, 17987, 18017, 18048, 
18078, 18109, 18140, 18170, 18201, 18231, 18262, 18293, 18322, 
18353, 18383, 18414), class = "Date"), value = c(-0.00114366147620304, 
0.0126827549762198, -0.00243520612280401, 0.0434176111595466, 
0.0151236631016043, -0.0162976376656515, 0.0119655258974145, 
-0.00901273358690258, -0.0245306633291614, -0.00342143529210504, 
0.0333876920436014, -0.0125415282392026, -0.00933636134241733, 
-0.0165562913907285, 0.00267633600966932, 0.0396073704150164, 
0.0359450057975816, 0.00423728813559321, -0.00780192659820078, 
-0.0112332504212469, -0.0255619573155887, -0.0060792804796802, 
0.0319229157938836, 0.0414907437479701, -0.00226085600686055, 
-0.00226597905922798, 0.0115122562455947, 0.0339888510374728, 
0.0228378884312992, -0.00366032210834555, -0.00631888317413665, 
-0.00591540964211767, -0.0219428741445998, -0.0031181078409005, 
0.0345590479096736, -0.0238920433596342, 0.000528820729772672, 
0.00188764723648438, -0.000602909036099164, 0.0220194555463389, 
0.0334243340957721, -0.021776381550764, 0.00481716663017306, 
-0.0106777075615603, -0.0246696035242291, 0.0045919903643481, 
0.0313225927313601, -0.0324783840732399, -0.00045058576148993, 
0.005709992486852, -0.00231585238308685, 0.0435791838262822, 
0.01305876443998, 0.0330759968836321, -0.0342108871520637, -0.00298147227940659, 
-0.0223567105731577, 0.0109970140557862, 0.0427892234548335, 
-0.0481486598507875, 0.000217722621380423, 0.00420838775214039, 
0.0057803468208093, 0.0211206896551723, 0.0429154354861405, -0.0168645439827307, 
0.00693014958144644, 0, -0.0151277683134583, 0.00518923406905136, 
0.114881607929515, -0.0831018089769711, -0.00989832334522933, 
0.000884113166485401, 0.0117551131344704, 0.0263935527199464, 
0.0129555715500884, -0.00148569213875072, 0.0108034674602149, 
-0.00454399999999999, -0.00784364150700789, 0.0259201658890618, 
0.123420919656392, -0.0650511638367255, -0.00727644476516931, 
0.00363460140537919, 0.00289715113471756, 0.0428502648050073, 
0.0111957525392428, 0.00239698664536014, -0.00142336597585968, 
-0.000912252693996196, -0.0311019802545226, 0.016668629991754, 
0.119170384102891, -0.0858266901335542, -0.00283125707814269, 
0.00800681431005112, 0.0104219480592642, 0.0361842105263157, 
0.019424266881894, -0.0203736936556529, 0.0450431034482759, 0.000206228088265537, 
-0.0197422680412371, 0.0202976284377137, 0.112714528681132, -0.105141269106068, 
-0.00175983436853, 0.0159182826921083, -0.0027050477211249, 0.0331115660184238, 
0.0237281418734829, -0.0127262169747411, 0.0131843356369161, 
0.00503095975232193, -0.00264728532922598, 0.0159741325225617, 
0.116901007030211, -0.0519712499468379, 0.00242250235521069, 
0.0017006041620049, 0.00272528258052995, 0.0332828372839067, 
0.011125005390022, -0.0110026013902512, 0.00948643870466981, 
0.00358805689633068, -0.00625665035113854, 0.0180315230426589, 
0.0245277462240734, -0.023612023653088, -0.00542541111157846, 
-0.00245263870094725, -0.00440864773208982, 0.0203099718981521, 
0.0239953261277803, -0.014345097399951, -0.000661539733730288, 
-0.0119569714522135, -0.00544365813826897, 0.0120415982484947, 
0.0275408744851686, -0.0334021620308514, -0.00665996481528019, 
-0.00476491671937596, 0.00665197864587741, 0.0243276232164653, 
0.0204626700086288, -0.0360378498087377, 0.0340434419381788, 
-0.0145425166633003, -0.0254970280795245, 0.0176250368064612, 
0.0221147486772486, -0.0256399886763456, -0.00772008467189644, 
0.00606516919730615, 0.0007068019291534, 0.0351073995595994, 
0.00923175724492253, 0.00707922367165126, -0.00477845351867945, 
0.00599182572120149, -0.0236667718523194, 0.0065449256625727, 
0.0355623344304408, -0.0265891472868217, -0.0014732818348332, 
0.00610120827850213, 0.00305192231470475, 0.0386059193108625, 
0.0218003348044438, -0.0084521726179394, -0.000638377769432985, 
-0.00578664562431896, -0.0276654446502136, 0.021844754538034, 
0.0322948761839552, -0.0302527820767927, 0.00349583919139729, 
0.00810329811806576, 0.00285467452954213, 0.0365556762425558, 
0.0163324299909666, -0.00284424218722223, 0.00303062716155034, 
0.000319920375373206, -0.0198642550015991, 0.0180552534261476, 
0.0247863247863247, -0.0288782318598833, 0.00393630345321161, 
0.000356442701835658, 0.001781578478532, 0.0285612662279922, 
0.0141780206100006, -0.0126500272776868, 0.0103947232102772, 
-0.000375965547884327, -0.00588094505419356, 0.0147893379191746, 
0.0335536349771226, -0.0312182324971306, -0.00132010967064955, 
-0.00325379609544474, 0.00459058759521214, 0.0379785397556105, 
0.0113158323821947, -0.0098349026183413, 0.00348454749731331, 
-0.00454338936846888, 0.00544435026406731, 0.0257773742745047, 
0.0252876469844481, -0.0299050437785177, -0.00527553549863347, 
0.0105431309904154, -0.00657603540942142, 0.0360257144675704, 
-0.018830251274805, -0.00281769512538743, 0.00106747040909227, 
-0.0162458836443469, -0.0259827206937226, 0.000229117570044624, 
0.00971890441441148, -0.0717850661135597, 0.0361020914074228, 
-0.00367312552653754, 0.000676452682134787, 0.0332589738389779, 
0.0153745502126268, -0.0158505154639176, 0.0106717297368077, 
-0.00634838375331992, -0.019916552578395, 0.0145009478830611, 
0.0169819362029964, -0.0248218948454273, -0.0111731843575419, 
0.0067194865108815, 0.000332071461778494, 0.037378834152171, 
-0.000832000000000055, -0.0136113246220856, 0.00769505503425427, 
-0.0124049490913778, -0.0154970474046524, 0.0189886002120891, 
0.0181144102247228, -0.0336037820226155, -0.00373504330005947, 
-0.00119438638399527, 0.00381996346121904, 0.0574123097286565, 
-0.00491315913002655, -0.0173595823636706, 0.0101773026947449, 
-0.0109301736155113, -0.0209167494154201, 0.0262055879081333, 
0.0131029425829694, -0.0251117125055069, -0.0164622336991608, 
0.00452904496225792, 0.00313643491897553, 0.0439356435643565, 
0.00324462608804166, -0.00964020275523214, 0.00775583257449686, 
-0.00685486383747747, -0.0244713559641087, 0.0245384961728952, 
0.0116457921335971, -0.0308427454387489, -0.00806813088301206, 
0.00313085017106718, 0.00714308697191024, 0.0450145362767962, 
-0.00446346682971566, -0.010809482864513, 0.0078542158201913, 
-0.0140458955798552, -0.0195882408072729, 0.0235166656044867, 
0.0131693648816937, -0.028516117137326, -0.00610469713743478, 
0.0063331423843167, 0.00284620979728656, 0.0493204250890857, 
-0.00168294515401957, -0.00996417712754749, 0.00513865239601063, 
-0.00916598602414009, -0.0214019661720706, 0.0317598976694848, 
-0.00257022769193549, -0.0212211241132602, -0.0066282599269033, 
-0.00152781242205036, 0.0120850638603505, 0.051928417155199, 
0.0134631742586455, -0.0279868025005788, 0.0096471639124609, 
-0.011884750361261, -0.0152808452217513, 0.0343092683518216, 
-0.00360428998417628, -0.014145810663765, 0.00832289242885276, 
-0.000266264311706732, 0.00727982954545459, 0.0542628826605558, 
-0.00607496168315447, -0.00757002271006812, 0.0130802045371077, 
-0.00833798103736749, -0.0152132954641321, 0.0388920616790405, 
-0.00898796107965483, -0.0113715157398419, -0.0044606536681161, 
0.00433973961562306, 0.0106060606060605, 0.0597479038258648, 
-0.00686402934241548, -0.0124248179803735, 0.0097764243929801, 
-0.0181996137872655, -0.0118819884143877, 0.0339477559033647, 
-0.0109707534481395, -0.0104258326000587, -0.0111284759646475, 
0.00307910297283298, 0.00842116701075746, 0.0490275308442434, 
-0.0161265471727184, -0.00652503001513804, 0.00811790668348045, 
-0.0104239960388816, -0.0140626234429726, 0.0282860119127113, 
-0.0142085303132631, -0.012384390398145, -0.0146207411755289, 
-0.0024097690412368, 0.0277114319834979, -0.00306351511950353, 
0.010357890275239, -0.00527005768222344, 0.0061286634525064, 
-0.0162199327188703, -0.00785344561887336, 0.0288945900000865, 
-0.0159828692064529, -0.00918254517100159, -0.0102873934446293, 
0.002780610100932, -0.0324306928884456, 0.0465067241012509, -0.0594878062153424
)), row.names = c(NA, -365L), class = c("tbl_df", "tbl", "data.frame"
), na.action = structure(c(`1` = 1L), class = "omit"))

**Comment by mdancho84** [comment]
Upon inspection, it doesn't seem like this is a bug or issue with the R package. I'm closing for now. Will reopen if it's a bug.
