### ISSUE TITLE
Speed of recursive forecasting has gotten worse

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime#219]
It looks like the speed of the `recursive()` forecasting has gotten worse.

**Comment by joranE** [comment]
Sorry if this is my fault! FWIW, I don't see any performance regression when I run some example models using the CRAN release versus the dev version for recursive models that forecast one row at a time, and I'm still seeing the performance improvements in the cases where the forecasts can be generated in chunks. If you have a specific example of a model that exhibits a performance regression I'd be happy to try to take a look.

**Comment by mdancho84** [comment]
I'm taking this one down - Performance looks OK.

**Comment by joranE** [comment]
I'm so relieved! I was really worried I'd somehow made things worse!
