### ISSUE TITLE
modeltime_calibrate

### ISSUE THREAD

**Issue by TDL77** [business-science/modeltime#23]
I am calibrating the model but when I run modeltime_calibrate I get the following error:
Error in eval(parse(text = text, keep.source = FALSE), envir) :
object 'summary_fun' not found
..same error as
https://www.business-science.io/code-tools/2020/06/29/introducing-modeltime.html

**Comment by mdancho84** [comment]
Can you please provide a reproducible example?

**Comment by TDL77** [comment]
library(tidymodels)
library(modeltime)
library(timetk)   
library(lubridate)
library(tidyverse)

setwd("C:/DATA")
# Get Your Data
dff <- readRDS("dff.RDS")
head(dff)
# Select date and count
dff_tbl <- dff %>%
  select(Date , Close ) %>%
  rename(date  = Date,
         value = Close)
bike_transactions_tbl <- as_tibble(dff_tbl)
bike_transactions_tbl

bike_transactions_tbl %>%
  plot_time_series(date, value, .interactive = FALSE)
# Train / Test
splits <- bike_transactions_tbl %>%
  time_series_split(assess = "10 months", cumulative = TRUE)
splits %>%
  tk_time_series_cv_plan() %>%
  plot_time_series_cv_plan(date, value, .interactive = FALSE)
# Modeling-----------------------------------------------------------------
# Auto ARIMA
model_fit_arima <- arima_reg() %>%
  set_engine("auto_arima") %>%
  fit(value ~ date, training(splits))
## frequency = 14 observations per 1 hour
model_fit_arima
# ARIMA(0,1,0)(0,0,1)[14]
# Prophet
model_fit_prophet <- prophet_reg() %>%
  set_engine("prophet", yearly.seasonality = TRUE ,  weekly.seasonality = "auto",
             daily.seasonality=TRUE ) %>%
  fit(value ~ date, training(splits))
model_fit_prophet  #Fit time:  7m 2.9s 
# Machine Learning Models------------------------------------------------
# Preprocessing Recipe
recipe_spec <- recipe(value ~ date, training(splits)) %>%
  step_timeseries_signature(date) %>%
  step_rm(contains("am.pm"), contains("hour"), contains("xts")) %>% 
  # step_fourier(date, period = c(30.42 , 91.25), K = 2) %>%  # ERROR !!
  step_dummy(all_nominal())
recipe_spec %>% prep() %>% juice()
# Elastic Net -----------------------------------------------------------------------
model_spec_glmnet <- linear_reg(penalty = 0.01, mixture = 0.5) %>%
  set_engine("glmnet")
workflow_fit_glmnet <- workflow() %>%
  add_model(model_spec_glmnet) %>%
  add_recipe(recipe_spec %>% step_rm(date)) %>%
  fit(training(splits))
# Random Forest ---------------------------------------------------------------------
model_spec_rf <- rand_forest(trees = 500, min_n = 50) %>%
  set_engine("randomForest")
workflow_fit_rf <- workflow() %>%
  add_model(model_spec_rf) %>%
  add_recipe(recipe_spec %>% step_rm(date)) %>%
  fit(training(splits))
# New Hybrid Models -----------------------------------------------------------------
# Prophet Boost
model_spec_prophet_boost <- prophet_boost() %>%
  set_engine("prophet_xgboost", yearly.seasonality = TRUE ,weekly.seasonality =TRUE ,
             daily.seasonality=TRUE) 
workflow_fit_prophet_boost <- workflow() %>%
  add_model(model_spec_prophet_boost) %>%
  add_recipe(recipe_spec) %>%
  fit(training(splits))
# The Modeltime Workflow ------------------------------------------------------------
model_table <- modeltime_table(
  model_fit_arima,
  model_fit_prophet,
  workflow_fit_glmnet,
  workflow_fit_rf,
  workflow_fit_prophet_boost)
model_table
# Calibration -----------------------------------------------------------------------
calibration_table <- model_table %>%
  modeltime_calibrate(testing(splits))
# Ошибка в eval(parse(text = text, keep.source = FALSE), envir) :   !!!!!!!!!
  # объект 'summary_fun' не найден
calibration_table
# Forecast (Testing Set) ------------------------------------------------------------
calibration_table %>%
  modeltime_forecast(actual_data = bike_transactions_tbl) %>%
  plot_modeltime_forecast(.interactive = FALSE)
# Accuracy (Testing Set) ------------------------------------------------------------
calibration_table %>%
  modeltime_accuracy() %>%
  table_modeltime_accuracy(.interactive = FALSE)
# Analyze Results -------------------------------------------------------------------
# Refit and Forecast Forward --------------------------------------------------------
calibration_table %>%
  # Remove ARIMA model with low accuracy
  filter(.model_id != 1) %>%
  # Refit and Forecast Forward
  modeltime_refit(bike_transactions_tbl) %>%
  modeltime_forecast(h = "12 months", actual_data = bike_transactions_tbl) %>%
  plot_modeltime_forecast(.interactive = FALSE)


[dff.zip](https://github.com/business-science/modeltime/files/5100686/dff.zip)

**Comment by TDL77** [comment]
all ok
