### ISSUE TITLE
All models failed Modeltime Calibration:

### ISSUE THREAD

**Issue by nomanres** [business-science/modeltime#231]
I have a set of equal univariate timeseries with id and prepared recipe like this:

rec_obj <- recipe(value ~ ., training(splits)) %>%
    step_mutate_at(id, fn = droplevels) %>%
    step_date(date, features = c("month", "quarter", "year")) %>%
    step_mutate(dt = as.numeric(date)) %>% 
    step_rm(date) %>%
    step_dummy(all_nominal_predictors(), one_hot = TRUE)

And I use code from Forecasting with Global Models ([modeltime](https://business-science.github.io/modeltime/index.html)
1.2.8.9000) with xgboost model. 
I cannot calibrate my model
calib_tbl <- model_tbl %>%
    modeltime_calibrate(
        new_data = testing(splits), 
        id       = "id"
    )

calib_tbl

**Comment by mdancho84** [comment]
Without a full reproducible example, I'm not able to help. 

Ideas: Try updating your R packages.
