### ISSUE TITLE
Refit and Forecast 1 day ahead with exogenous regressors

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#24]
**_Ubuntu: 16.4 LTS, R: 4.0.2, modeltime: 0.0.2_**

Thank you Matt for the marvelous code.

I can't find any documentation/information how to refit and forecast 1 day ahead, 
using exogenous regressors. 

In the forecast package by Prof. Hyndman I would say: 

`arima.forecast <- forecast(arima.model,h=myH,xreg=newRegressors,biasadj=T)`

When I say...
```
            unseenPredict<-calibration_table %>%
                modeltime_refit(model_table,data=allData) %>%
                #modeltime_forecast(h="3 months",actual_data=allData)# %>%
                modeltime_forecast(new_data=testing(splits),actual_data=allData)# %>%

```
... I get data by type actual and forecast until the last day contained in splits.
But I want to forecast one unseen day ahead, including exogenous regressors used while training.

In regard to "modeltime_forecast()" I read about a future tibble. But then the documentation PDF ends... "Forecasting Future Data: See future_frame() for creating future tibbles." "future_frame()" seems to be a dead link.

Are there any hints available- or a small code example?

Thank you.

**Comment by Vidaringa** [comment]
> For a 1-step or multi-step ahead forecasts that include XREGS (e.g. lags, events, etc), you need to use `new_data` providing all columns with the exception of the target column (optionally the target can be encoded as NA values). This means you need to supply the Xregs as part of the future data frame.

How does this work if the lags are of the outcome variable you are trying to forecast? This was helpful in the M5 competition I think. I tried to include step_lag(all_outcomes(), lag = 1:7) but this alone will not work. What other steps to I have to take to make a forecast e.g. 14 days into the future?

**Comment by mdancho84** [comment]
Don't create lags as a preprocessing step inside of your preprocessing recipe. Rather create the lags outside of your recipe.  

In the upcoming Time Series course, I teach you to:
1. Extend your data frame through your forecast window
2. Add lags and any external regressors. 
3. Split into a data_prepared_tbl and a forecast_tbl. <-- Now you have lags in your future data 
4. Split data_prepared_tbl into train/test <-- Now you have training set that you can model with, and test for calibration
5. Apply recipes to training set <-- Don't do lags here, this is too late.

**Comment by Vidaringa** [comment]
Ok I see. Looking forward to the course!

**Comment by mdancho84** [comment]
Yes - There is a strategy. :)
