### ISSUE TITLE
Prophet Boost issue

### ISSUE THREAD

**Issue by nevesjcg** [business-science/modeltime#241]
here was 1 warning in `mutate()`.
ℹ In argument: `object = purrr::map(call_info, eval_call_info)`.
Caused by warning:
! The `default` argument of `new_qual_param()` is deprecated as of dials 1.1.0.
ℹ The deprecated feature was likely used in the modeltime package.
  Please report the issue at <https://github.com/business-science/modeltime/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
> toc()
15.119 sec elapsed
> lifecycle::last_lifecycle_warnings()
list()

**Comment by marcozanotti** [comment]
not only in prophet boost but happens everytime using `hardhat::extract_parameter_set_dials(model_spec)`

**Comment by mdancho84** [comment]
Will need to evaluate. Looks like some of the functions may be deprecated in dials. Have you tried the latest development version?
