### ISSUE TITLE
Extracting fitted data from nested forecasting model

### ISSUE THREAD

**Issue by Zuki27** [business-science/modeltime#242]
Hi Matt

Can I please ask how to go about doing this.

I have been going a lot of searching online and in package documentation, etc. about extracting the model fitted values when working with nested data of many time series.

**Comment by spsanderson** [comment]
As far as i know these are tidymodels frameworks so pulling out the fitted workflow and unnesting it with tidyr should donitSent from my iPhonewww.spsanderson.comOn Jan 23, 2024, at 4:41 PM, Zuki27 ***@***.***> wrote:﻿
Closed #242 as completed.
