### ISSUE TITLE
Is it possible to inlclude the long short-term memory (LSTM) network in the package?

### ISSUE THREAD

**Issue by Freestyleyang** [business-science/modeltime#245]
@mdancho84 

Hi There,

Thank you for your amazing work in developing the package. In terms of the time series forcasting algorithm, is it possible to inlclude the long short-term memory (LSTM) network in the package? Thanks. 

Regards,
Yang

**Comment by joranE** [comment]
You should look at the [modeltime.gluonts](https://business-science.github.io/modeltime.gluonts/) extension package (although fair warning, in my experience it was fairly finicky to get working).

**Comment by mdancho84** [comment]
The answer is modeltime.gluonts as described by @joranE. Note, do not use the CRAN version. Follow installation instructions here: https://business-science.github.io/modeltime.gluonts/
