### ISSUE TITLE
Tune prophet within modeltime model

### ISSUE THREAD

**Issue by Patrikios** [business-science/modeltime#246]
As the documentation does not povide a an example for hyperparameter tuning a prophet model, I tired a simple snippet like follows:

```r
 modeltime::prophet_reg(
    growth = growth(values = c("linear", "logistic")),
    changepoint_num = changepoint_num(range = c(0L, 50L), trans = NULL)
  ) |>
    parsnip::set_engine(
      engine = "prophet",
      holidays = generated_holidays
    ) |>
    fit(target_var ~ .,
        data = split_train
    )
```

which fails with

```r
growth must be 'linear' or 'logistic'. Defaulting to 'linear'.
Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
Fehler in m$n.changepoints + 1 : 
  nicht-numerisches Argument für binären Operator
```

Is this usage correc?

**Comment by joranE** [comment]
In general you specify a hyperparameter for tuning by passing, e.g. `growth = tune()`. There is a full walkthrough of the process [here](https://www.tidymodels.org/start/tuning/).

**Comment by FColicino** [comment]
Alternatively, you can use `create_table_grid` to create a list of model that you need to train.
Below the code:

```{r}
library(modeltime)
library(tidymodels)


m750

models <- 
  grid_regular(
    changepoint_num(),
    growth(),
    levels = 3) |>
  create_model_grid(
    f_model_spec = prophet_reg,
    engine_name  = "prophet",
    mode         = "regression"
  ) |>
  select(.models) |>
  pull() # or pluck(1)

preprocessing <-
  list(basic_preproc = recipe(value ~ date, data = m750))
  
wf <- workflow_set(preproc = preprocessing,
                   models = models)

modeltime_fit_workflowset(wf, data = m750)
```

**Comment by mdancho84** [comment]
If you are doing a single global model, then the tidymodels hyperparameter tuning resource can be used (thanks @joranE): https://www.tidymodels.org/start/tuning/ 

If you are doing nested forecasting or if you want to create combinations of models, I have this resource: https://business-science.github.io/modeltime/articles/parallel-processing.html
