### ISSUE TITLE
Error occurred when using 'fit-forecast' workflow

### ISSUE THREAD

**Issue by jpzhangvincent** [business-science/modeltime#33]
I installed the development version from GitHub and tried to forecast a time series using 'auto.rima' for intermittent demand forecasting. But I got the following error.
<img width="558" alt="Screen Shot 2020-08-30 at 4 51 00 PM" src="https://user-images.githubusercontent.com/7220686/91673314-7b4a4a80-eae8-11ea-90b4-fcd699378db8.png">

Here is my testing example.
[test_ts.csv.zip](https://github.com/business-science/modeltime/files/5147789/test_ts.csv.zip)

**Comment by jpzhangvincent** [comment]
Oh I realized the time series data frame is a `tsibble` object. I have to convert to `tibble` object and then it works.

**Comment by mdancho84** [comment]
Yes, you'll need to work exclusively with `data.frame` or `tibble` objects. `tsibble` have different properties making it difficult to predict how they will respond to the modeltime workflow.
