### ISSUE TITLE
Parameter Tuning

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime#4]
- [ ]  Determine if `tune` helpers needed to be added to `modeltime`.
- [ ]  Parameter tuning vignette

**Comment by Teett** [comment]
Hi @mdancho84, hope you are doing great. I think it's safe to say that tuning is quite an important step to make ML algorithms perform at their best in time series.

It would be great if some documentation on this topic could be added. I haven't even been able to find any functions (or examples) related to the topic, even though it's mentioned on your premium courses.

+1

**Comment by mdancho84** [comment]
This is now complete. I have added:
- [Tuning & Parallel Processing Article](https://business-science.github.io/modeltime/articles/parallel-processing.html).
- New functionality to help with Parallel Processing and Tuning: https://business-science.github.io/modeltime/reference/index.html#section-parallel-processing
