### ISSUE TITLE
Add MDFA

### ISSUE THREAD

**Issue by SamoPP** [business-science/modeltime#40]
It would be great if you could add MDFA from Marc Wildi: https://github.com/wiaidp/MDFA . Details here https://github.com/wiaidp/MDFA-Legacy and https://github.com/wiaidp/Tutorials .

**Comment by mdancho84** [comment]
Hey, I'd recommend creating a Modeltime Extension for this. I'm don't have the capacity for adding models that aren't currently on the Modeltime Roadmap (#5). I have added a ["How To Extend Modeltime Guide"](https://business-science.github.io/modeltime/articles/extending-modeltime.html) and you can see how to make Modeltime Extensions by following what I've done in `modeltime` and `modeltime.gluonts`.
