### ISSUE TITLE
Error while loading modeltime: The values passed to `set_encoding()` are missing arguments: `allow_sparse_x`

### ISSUE THREAD

**Issue by cho7tom** [business-science/modeltime#42]
Hi Matt, I've just installed your new modeltime.ensemble package.
However it seems I now get an error trying to load modeltime (not sure these two facts are related actually)
Do you have any recommendation to make it work again (I removed / reinstalled but it did not solve the issue)
I'm using the latest version of R (4.0.3)
Many thanks in advance for your view on this,
Thomas
![Capture d’écran 2020-10-13 à 12 35 01](https://user-images.githubusercontent.com/4041568/95858923-2132db00-0d5e-11eb-958a-60a4b716d807.png)
![Capture d’écran 2020-10-13 à 14 13 03](https://user-images.githubusercontent.com/4041568/95859006-3c054f80-0d5e-11eb-9373-e3d6f8d8fe7f.png)

**Comment by mdancho84** [comment]
## Problem:
This is related to `set_encodings()` enhancement, which is in the development version of `parsnip 1.0.3.9000`. Refer to tidymodels/parsnip#376.

## Solution:
1. Downgrade to `parsnip 0.1.3` using `install.packages("parsnip")
2. Wait until I accept #41 - Should be later this week.

**Comment by mdancho84** [comment]
I just accepted #41 so you can resolve by using `remotes::install_github("business-science/modeltime")` with `parsnip (>= 0.1.3.9000)`

**Comment by dseynaev** [comment]
I just hit this issue after `parsnip` released `0.1.4` to CRAN so more people are about to hit this. Any idea on how far `modeltime` is from a `0.2.2`?

**Comment by mdancho84** [comment]
`modeltime` 0.3.0 has just shipped to CRAN. It fixes this issue. Plus it has several enhancements to work with Panel Data!
