### ISSUE TITLE
modeltime.rdb is corrupt

### ISSUE THREAD

**Issue by jelewis** [business-science/modeltime#45]
>library(modeltime)
Error: package or namespace load failed for ‘modeltime’ in get(Info[i, 1], envir = env):
 lazy-load database 'C:/R-4.0.2/library/modeltime/R/modeltime.rdb' is corrupt
In addition: Warning messages:
1: package ‘modeltime’ was built under R version 4.0.3
2: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by mdancho84** [comment]
Are you able to install from github? `devtools::install_github("business-science/modeltime")`

**Comment by jelewis** [comment]
Hi,
I tried with the code line from github issue page:
remotes::install_github("business-science/modeltime")
and received the same error as previously and then when you wrote I tried
it again but as you can see there was no change so the package didn't need
to be installed.

devtools::install_github("business-science/modeltime")
Skipping install of 'modeltime' from a github remote, the SHA1 (3f0e6aad)
has not changed since last install.
  Use `force = TRUE` to force installation

**Comment by mdancho84** [comment]
Try `force = TRUE`. This will force a new installation.

**Comment by jelewis** [comment]
Hi again,
It has loaded fine now. Thanks a lot for your quick help.
John Lewis

**Comment by mdancho84** [comment]
Sounds good. Closing the issue.
