### ISSUE TITLE
Modeltime with R 3.6.2 - not available

### ISSUE THREAD

**Issue by sfitzpat1990** [business-science/modeltime#52]
I am using R version 3.6.2 and getting the following error.  When I look at the package on CRAN it says it is available for R (≥ 3.5.0).  Are there known issues with 3.6.2?

Error installing R package: Could not install package with error: 1: package ‘Modeltime’ is not available (for R version 3.6.2)

**Comment by mdancho84** [comment]
That shouldn't be the case. I test on Travis using 3.6.0. It's passed it's latest check (yesterday). 

![image](https://user-images.githubusercontent.com/13734662/101649621-1b2d4380-3a09-11eb-8422-f209b7ed2286.png)

**Comment by sfitzpat1990** [comment]
Maybe that error message isn't the real issue.  I am using Databricks and trying to install the library.  Do you know if people have had luck installing in databricks?  I'll keep digging and see if something else is going on.

**Comment by mdancho84** [comment]
I'm closing this as it seems to be local to your setup. Let me know if you do find a solution.
