### ISSUE TITLE
Model calibration fails on my data

### ISSUE THREAD

**Issue by sbannist** [business-science/modeltime#57]
Here is a short trace:
<error/rlang_error>
All models failed Modeltime Calibration.
Backtrace:
 1. modeltime::modeltime_calibrate(...)
 2. modeltime:::modeltime_calibrate.mdl_time_tbl(...)
 3. modeltime:::validate_modeltime_calibration(ret)
Run `rlang::last_trace()` to see the full context.

NB: I had to comment out wflw_fit_mars as the mars model will not fit (a separate issue, not yet reported).

**Comment by mdancho84** [comment]
Hi, 

Do you have a minimal reproducible example so I can attempt to replicate your error?

Thanks, Matt
