### ISSUE TITLE
have you really run the code on your web site?

### ISSUE THREAD

**Issue by bigdataman2015** [business-science/modeltime#6]
have you really run the code on your web site?

https://www.business-science.io/code-tools/2020/06/29/introducing-modeltime.html

too much bug.

**Comment by mdancho84** [comment]
Try installing the development version of timetk

**Comment by mdancho84** [comment]
I assume the `time_series_splits()` function is giving you the issue. I've addressed here:

![image](https://user-images.githubusercontent.com/13734662/86109857-d59c4000-ba92-11ea-96a9-bc3cf44dd221.png)
