### ISSUE TITLE
H2O- AutoML

### ISSUE THREAD

**Issue by Shafi2016** [business-science/modeltime#61]
Hello  @mdancho84 ,   Thanks for the nice work!. It would be very good if you add H2O packages such as AutoML H2O. That also allows for the ensemble. If you can combine it with your ensemble average, weighted average, etc. I think integrating it with H2O would be a remarkable achievement.

**Comment by mdancho84** [comment]
Thanks for your help @Shafi2016 . I'm just adding a link and closing this since we are developing `modeltime.h2o`. Link to the Modeltime H2O Roadmap (modeltime.h2o#1).
