### ISSUE TITLE
Error: The `period` argument could not be parsed.

### ISSUE THREAD

**Issue by JavierLopatin** [business-science/modeltime#65]
Hi,

I'm trying to run the example code of the "_Getting Started with Modeltime_" section, using the m750 test dataset. I'm always having the error: "Error: The `period` argument could not be parsed." when fitting any model, e.g.:

```R
# Model 1: auto_arima ----
model_fit_arima_no_boost <- arima_reg() %>%
    set_engine(engine = "auto_arima") %>%
    fit(value ~ date, data = training(splits))
#> frequency = 12 observations per 1 year
```

>> Error: The `period` argument could not be parsed.
Run `rlang::last_error()` to see where the error occurred.
Además: Warning messages:
1: In stringr::str_detect(., "week") :
  reiniciar evaluación premisa interrumpida
2: In stringr::str_detect(., "week") : internal error -3 in R_decompress1
Timing stopped at: 0.173 0 0.172

I tried to set the _seasonal_period_ argument manually, but it did not work either. 

I'm using a Ubuntu 20.10 machine with the 'modeltime' development version (i.e., installed as _remotes::install_github("business-science/modeltime"))_. All packages were installed correctly. 

I appreciate the help, the package seems to be very helpful.

Cheers, Javier

**Comment by mdancho84** [comment]
What version of `timetk`? The period parsing is handled with that package. It's easiest to use `devtools::session_info()` with all of your libraries that you are using loaded.

**Comment by JavierLopatin** [comment]
Hi, _timetk_ version * 2.6.1. Thanks.

**Comment by mdancho84** [comment]
Hi, is this still an issue? If so I'm not able to replicate using:
- modeltime 0.6.0
- timetk 2.6.1

I'm closing and will reopen if still an unresolved issue. 

``` r
library(tidyverse)
library(tidymodels)
library(modeltime)
library(timetk)

m750_splits
#> <Analysis/Assess/Total>
#> <282/24/306>

# Model 1: auto_arima ----
model_fit_arima_no_boost <- arima_reg() %>%
    set_engine(engine = "auto_arima") %>%
    fit(value ~ date, data = training(m750_splits))
#> frequency = 12 observations per 1 year

modeltime_table(
    model_fit_arima_no_boost
) %>%
    modeltime_forecast(
        new_data    = testing(m750_splits),
        actual_data = m750
    ) %>%
    plot_modeltime_forecast(.interactive = FALSE)
#> Warning: Expecting the following names to be in the data frame: .conf_hi, .conf_lo. 
#> Proceeding with '.conf_interval_show = FALSE' to visualize the forecast without confidence intervals.
#> Alternatively, try using `modeltime_calibrate()` before forecasting to add confidence intervals.
```

![](https://i.imgur.com/MoFWCvG.png)

<sup>Created on 2021-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
