### ISSUE TITLE
plot_modeltime_forecast group = 1

### ISSUE THREAD

**Issue by jrosell** [business-science/modeltime#66]
If you are doing a prediction for only one month you may need to change plot_modeltime_forecast to use geom_point and ggplotly.

```
p <- ggplot(data, aes(x = .index, y = .value, colour = .model_desc)) + geom_point() 
ggplotly(p)
```

**Comment by mdancho84** [comment]
Yep - this is a good call.

**Comment by mdancho84** [comment]
This should be fixed now in the `modeltime` development version (0.4.1.9000). If you have a single point forecast, your plot will now display a point using `geom_point()` as opposed to an invisible line of one point. 

![image](https://user-images.githubusercontent.com/13734662/110673476-d26b5f00-819e-11eb-837b-29187fbec3f2.png)
