### ISSUE TITLE
Encountered Problem - could not find function "time_series_split"

### ISSUE THREAD

**Issue by SHRINIVASDHARMADHIKARI** [business-science/modeltime#7]
splits <- bike_transactions_tbl %>%
+   time_series_split(assess = "3 months", cumulative = TRUE)

Error in time_series_split(., assess = "3 months", cumulative = TRUE) : 
  could not find function "time_series_split"

**Comment by EmilHvitfeldt** [comment]
The `time_series_split()` function comes from the timetk package

https://business-science.github.io/timetk/reference/time_series_split.html

Make sure to load in the packages

```r
library(timetk)
```

**Comment by mdancho84** [comment]
Yes sorry it’s in the development version of timetk.

**Comment by mdancho84** [comment]
I've added a comment to update to the development version of `timetk`. This should fix. Let me know if you see anything else. 

![image](https://user-images.githubusercontent.com/13734662/86109991-febcd080-ba92-11ea-9ca0-3ed798b5fd79.png)

**Comment by Libardo1** [comment]
devtools::install_github("business-science/timetk")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: NULL
  error: package ‘backports’ does not have a namespace

**Comment by mdancho84** [comment]
You’ll need to install the backports pkg. Try install.packages(“backports”)

**Comment by Libardo1** [comment]
After install backports,
devtools::install_github("business-science/timetk")
Error: package ‘fs’ does not have a namespace

**Comment by mdancho84** [comment]
Ok, you should know what to do now by the error message.

**Comment by mdancho84** [comment]
This is taken care of on CRAN now. Just use `install.packages("timetk")` and make sure you use version 2.1.0 or later.
