### ISSUE TITLE
updates for upcoming parsnip

### ISSUE THREAD

**Issue by topepo** [business-science/modeltime#8]
I'll be sending `parsnip` 0.1.2 to CRAN very soon and it has some differences in how to choose encodings from how `modeltime` currently does it. 

Using `arima_reg` as an example, the model definition should use the new `set_encoding()` interface (rather than passing `indicators` directly). To make sure that `parsnip` (and, soon `workflows`) does no modifications to the predictors columns, use

```r
set_encoding(
  model = "arima_reg",
  eng = "auto_arima",
  mode = "regression",
  options = list(
    predictor_indicators = "none",
    compute_intercept = FALSE,
    remove_intercept = FALSE
  )
)
```

They same type of declaration is required for each engine/model combination. 

The current GH version of `parsnip` can be used for testing.

**Comment by mdancho84** [comment]
Thanks Max. I'm on it. I'll work on the updates.

**Comment by mdancho84** [comment]
@topepo I've updated. 2 minor issues in case you get this from others:

- __mars() models__ handle dates and features with `model.matrix.earth`. In case anyone gets the error, just tell them to use the workflows interface. Reference tidymodels/parsnip#341.
- __Knitting with `set_encodings()`:__ For some reason, I couldn't get my vignette, `extending_model_time.Rmd` to knit. It worked fine when I run code chunks locally, but knitting caused an error that I couldn't fix - training and predictions were causing an error that the date column was not present. My bandaid solution was to save the intermediate steps as `.rds` files and read them in the appropriate spots. 

![image](https://user-images.githubusercontent.com/13734662/86478310-15c02480-bd18-11ea-80bb-d2b616ca3a3d.png)

**Comment by topepo** [comment]
New `parsnip` was accepted to CRAN

**Comment by mdancho84** [comment]
Nice work. Will send modeltime 0.0.2 to CRAN shortly.

**Comment by mdancho84** [comment]
Modeltime 0.0.2 is on CRAN, which incorporates `parsnip` 0.1.2. We are good to go.
