### ISSUE TITLE
Error installing modeltime

### ISSUE THREAD

**Issue by joanaleite** [business-science/modeltime#83]
I am using R version 4.0.4, and I get an error trying to install the new version of modeltime (version 0.5.0). The error seems related to other packages, but, still, the new version of modeltime is not instalable.

> install.packages("modeltime")

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/User/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependency ‘yardstick’

  There are binary versions available but the source versions are later:
          binary source needs_compilation
yardstick  0.0.7  0.0.8              TRUE
modeltime  0.4.2  0.5.0             FALSE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/yardstick_0.0.7.zip'
Content type 'application/zip' length 800469 bytes (781 KB)
downloaded 781 KB

package ‘yardstick’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\User\AppData\Local\Temp\Rtmpkzp8YE\downloaded_packages
installing the source package ‘modeltime’

trying URL 'https://cran.rstudio.com/src/contrib/modeltime_0.5.0.tar.gz'
Content type 'application/x-gzip' length 4766266 bytes (4.5 MB)
downloaded 4.5 MB

* installing *source* package 'modeltime' ...
** package 'modeltime' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'yardstick' 0.0.7 is being loaded, but >= 0.0.8 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'modeltime'
* removing 'C:/Users/User/Documents/R/win-library/4.0/modeltime'
Warning in install.packages :
  installation of package ‘modeltime’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\User\AppData\Local\Temp\Rtmpkzp8YE\downloaded_packages’

**Comment by mdancho84** [comment]
I'm seeing this:

> WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

Maybe try installing Rtools
