### ISSUE TITLE
Support for workflowsets

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime#85]
Add support for workflowsets https://workflowsets.tidymodels.org/

**Comment by AlbertoAlmuinha** [comment]
I was planning on commenting to you about this package, glad to see it's already posted here! What are the plans for this? Seems like a really exciting package!

**Comment by mdancho84** [comment]
I think we can just convert the `workflowset` to a modeltime table. Need to investigate though. Top priority is recursive ensemble for shore. 

Once finished I'll take a look at `workflowsets`. Also, I'll be doing a Learning Lab on workflowsets. I'll know more then.

**Comment by rafzamb** [comment]
Hi @mdancho84  , that development was already developed recently in sknifedatar. The individual focus of a workflowset on an individual series is ending. A workflowset approach to multiple series (workflowsets + modeltime_multifit) will be ready in a couple of days.

Some use cases will be published in the next few weeks and will also be sent to CRAN.

If you want to review it and give me any suggestions, I would be grateful.

https://github.com/rafzamb/sknifedatar

**Comment by mdancho84** [comment]
This is good. I saw the article here. https://rafael-zambrano-blog-ds.netlify.app/posts/workflowsets_timeseries/

**Comment by mdancho84** [comment]
Done. https://business-science.github.io/modeltime/reference/modeltime_fit_workflowset.html
