### ISSUE TITLE
Getting Started with Modeltime: Some Notes

### ISSUE THREAD

**Issue by peterhaglich** [business-science/modeltime#9]
Thank you for the page walking through Modeltime.  I found two minor items that you may consider changing in the walkthrough text.

1. In the script `m750 <- m4_monthly %>% filter(id == "M750")` I received an error because `filter` tried to call `stats::filter`.  That went away when I invoked `dplyr::filter`.
2.  The comment says split 80/20 but the code calls for a 90/10 split with the argument `prop=0.9`.

**Comment by mdancho84** [comment]
Thanks @peterhaglich I'll fix this in the docs. Appreciate the heads up.

**Comment by mdancho84** [comment]
This should be fixed provided you use:

```
# Time Series ML
library(tidymodels)
library(modeltime)

# Core 
library(tidyverse)
library(lubridate)
library(timetk)

```
