### ISSUE TITLE
Lagged Forecast - Error: All models failed Modeltime Calibration. Solution: Use Recursive

### ISSUE THREAD

**Issue by jkr216** [business-science/modeltime#95]
library(tidyverse)
library(tidyquant)
library(timetk)
library(tidymodels)
library(modeltime)
library(modeltime.resample)

fred_reprex <- 
  "NCBEILQ027S"%>% 
  tq_get(get = 'economic.data', from = "1980-01-01")

sp_500_reprex <- 
  "VFINX" %>% 
tq_get(get = 'stock.prices', from = "1980-01-01") %>% 
  summarise_by_time(.date_var = date, 
                    .by = "month",
                    first_month_price = first(close),
                    .type = "floor") %>% 
  arrange(date) %>% 
  mutate(ten_years_return     =  lead(first_month_price, 120)/first_month_price - 1,
         ten_years_annualized =  (1 + ten_years_return)^(365/3650)            -1) 

data_joined <- 
sp_500_reprex %>% 
left_join(
fred_reprex %>% 
  select(date, value = price), 
by = "date"
) %>% 
  fill(value, 
       .direction = "down")

splits <- 
  time_series_split(data_joined, assess = "6 months", cumulative = TRUE)

recipe_lags <- recipe(ten_years_annualized ~ ., data = training(splits)) %>%
step_lag(value, lag = 2:3) %>%
   step_naomit(contains("lag")) 

model_spec_lm <- linear_reg() %>%
    set_engine("lm")

sp_500_lm <- 
  workflow() %>%
    add_model(model_spec_lm) %>%
    add_recipe(recipe_lags) %>%
    fit(training(splits))

sp_500_model_tbl <- 
modeltime_table(
    sp_500_lm
)

sp_500_model_tbl %>%
    modeltime_calibrate(new_data = testing(splits)) %>%
    modeltime_accuracy(
        metric_set = metric_set(mae, rmse, rsq)
    )

**Comment by jkr216** [comment]
update: removing step_lag() fixes this issue. but not sure why adding the lags throws the error at the calibration stage.

**Comment by mdancho84** [comment]
Hey, this is a `recursive()` forecast because your lags are < forecast horizon. We have support for this now. Simply follow the steps outlined in our [Autoregressive Forecasting with Recursive](https://business-science.github.io/modeltime/articles/recursive-forecasting.html) article. 

Also, keep in mind that you need to be very careful using `step_lag()` inside of preprocessing recipes. @DavisVaughan and I discussed this here. https://gist.github.com/DavisVaughan/433dbdceb439c9be30ddcc78d836450d

**Comment by mdancho84** [comment]
@jkr216 we just added a really good article on recursive forecasting that should help you with this: https://www.business-science.io/code-tools/2021/04/08/autoregressive-machine-learning.html

**Comment by mdancho84** [comment]
I'm closing this issue, since it's now solved with the new `recursive()` function.

**Comment by jkr216** [comment]
thanks case closed!
