### ISSUE TITLE
Help about model

### ISSUE THREAD

**Issue by freebooterish** [business-science/modeltime#97]
If I have multiple columns of relevant data, such as accounts receivable and actual receipts, I only want to predict the actual receipts this month, and I know the accounts receivable this month, how should I model with modeltime? thanks.
for example
column1 column2
0.2          0.3
0.6          0.6
0.7          0.8
...             ...
0.9           ??  (Need to predict，current month)

**Comment by mdancho84** [comment]
Hi @freebooterish You can do exactly what you need to do - forecast with `modeltime`. But, you'll have to learn. The good news is that I have a whole course (that's fantastic) that teaches time series analysis and forecasting. It will make you quite valuable to your organization. Here is the link: https://university.business-science.io/p/ds4b-203-r-high-performance-time-series-forecasting/
